track decisions
OpenImaging/miqa pull request #1
Opened 2021-05-28 16:56 UTC by venkatabhishek

Overall changes allow for multiple decisions to be added to a scan (i.e. tracking history of decisions similar to scan notes) 
- Remove decision field from scan
- Created annotation model to capture a single decision (fields: creator, created, scan, decision)
- Created annotation view set and updated scan serialization for retrieving decisions
- Created endpoint to add a decision to an existing scan

Note: Included migration for model changes
Note 2: I will create PR for corresponding frontend changes once the new repo is setup

2021-05-28 19:37 UTC, venkatabhishek commented
Is there any reason the migration check fails when the migration file is there?

2021-05-28 21:32 UTC, zachmullen commented
Normally that would indicate that you modified something in your model after making the migration script. The way to resolve that would typically be to delete the migration file and re-run `makemigrations`, and of course don't forget to `tox -e format` after generating migrations.

2021-05-28 21:51 UTC, zachmullen commented on miqa/core/models/annotation.py
> +    NONE = '-'
I guess we still need an explicit `NONE`, if only for the case where an annotation was added, but then someone wishes to explicitly unset it.

2021-05-28 21:53 UTC, zachmullen requested changes
This looks great @venkatabhishek . Just a couple minor details and then re-run the migration.

2021-05-28 21:53 UTC, zachmullen commented on miqa/core/rest/scan.py
> +        print(serializer.validated_data)
Let's remove this `print`

2021-05-28 21:53 UTC, zachmullen commented on miqa/core/models/annotation.py
> +
I believe all our other models are using a UUID primary key, so for consistency let's go ahead and do that here too.

2021-06-01 14:52 UTC, zachmullen approved these changes

2021-06-01 14:52 UTC, zachmullen commented on miqa/core/models/annotation.py
> +
This is looking good. Let's add `Meta.ordering = ['-created']` and add the composite index for our main query case:

```python
Meta.indexes = [
    models.Index(fields=['scan', '-created']),
]
```

2021-06-01 17:15 UTC, zachmullen approved these changes

2021-06-02 19:42 UTC, zachmullen commented
@venkatabhishek when you get a chance, could you resolve conflicts / rebase this?

2021-06-03 18:44 UTC, zachmullen approved these changes
LGTM.

Note that this migration will clobber the pending migration on your other branch.

2021-06-08 18:20 UTC, zachmullen approved these changes

2021-06-08 18:29 UTC, merged