add email
OpenImaging/miqa pull request #19
Opened 2021-06-04 17:41 UTC by venkatabhishek

Resolves #2

Important notes:
- Currently, emails are just being printed to console, we would need a running SMTP server or provider to send them
- Screenshot attachment logic assumes images are mime type 'image/*' where * is 'jpeg', 'png', or some other image mime type

2021-06-04 17:44 UTC, zachmullen requested changes
LGTM other than the print statement

2021-06-04 17:44 UTC, zachmullen commented on miqa/core/rest/email.py
> +        print(request.data['screenshots'])
Remove `print`

2021-06-04 18:02 UTC, venkatabhishek commented
Maybe not super necessary but I also used a more accurate regex for data urls according to this [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)

2021-06-04 18:05 UTC, zachmullen commented on miqa/core/rest/email.py
> +                r'^data:(?P<mime>[\w/\-\.]+);?(\w+),(?P<data>.*)$', screenshot['dataURL']
If you use `re.fullmatch` rather than `re.search` you can omit the `^` / `$`.

2021-06-04 18:11 UTC, zachmullen approved these changes

2021-06-04 18:48 UTC, aashish24 commented on miqa/core/rest/email.py
> +            'example@kitware.com',  # TODO: replace
I believe @scottwittenburg had done something to this end

2021-06-08 17:26 UTC, zachmullen requested changes

2021-06-08 17:26 UTC, zachmullen commented on miqa/core/rest/email.py
> +            'example@kitware.com',  # TODO: replace
We can use the django setting `DEFAULT_FROM_EMAIL` for this. https://github.com/girder/django-composed-configuration/blob/master/composed_configuration/_email.py#L42

2021-06-11 21:29 UTC, dchiquito approved these changes

2021-06-17 16:21 UTC, merged