Production docker compose
OpenImaging/miqa pull request #60
Opened 2021-07-06 00:04 UTC by dchiquito

`miqa-web` was already copied into the `client` directory in #59.

* Add a new directory `prod` which contains all the docker/docker-compose/documentation stuff
* The docker image builds the django app, builds the web client, then plops the built artifacts into Django's `staticfiles`. Django's whitenoise app will then serve it under `/static/`. The frontend configuration has been updated to use relative URLs since Django and the web client are now hosted on the same domain/port.
  * To get the `index.html` to be served from `/` rather than `/static/index.html`, I registered `staticfiles` as a template directory, then created a `TemplateView` which served `index.html` and registered it with the url `/`. This will technically break in development, but in development we use `npm run serve` anyway so it doesn't really matter.
* I added a new configuration that does not have any of the extra `composed-configuration` cruft (minio, Sentry, etc.)
* I added a `prod/README.md` that explicitly lists all the setup steps.

Things that are not yet finished:
- [ ] HTTPS. I developed this without the `HttpsMixin`. I ran into problems when trying to log in: after successfully authenticating and authorizing the app, Django refused to redirect me to the app with `ERROR Redirect to scheme 'http' is not permitted`. Including `HttpsMixin` doesn't work locally since nothing is there to handle the SSL termination.
I assume Jim will be using nginx or something to provide SSL termination, so it's possible that everything will just work when he deploys it.
- [ ] A WSGI server. The container work by running `./manage.py runserver 0.0.0.0:8000`. This is likely fine for now, but we should see about installing+running a real WSGI server instead.
- [ ] The logout button wasn't working for me when I tested it, but there were no console or network errors. Something to look into.

2021-07-06 00:15 UTC, zachmullen requested changes

2021-07-06 00:15 UTC, zachmullen commented on miqa/settings.py
> +            str(Path(configuration.BASE_DIR) / 'staticfiles'),
`BASE_DIR` is already a `Path`, and this config value supports paths.

```suggestion
            configuration.BASE_DIR / 'staticfiles',
```

2021-07-06 00:15 UTC, zachmullen commented on prod/README.md
> +The app should now be running and accessible in your browser.
I'd like to add an idempotent manage.py command to set up the OAuth application with all these knobs hard-coded to the right value.

2021-07-07 21:21 UTC, venkatabhishek reviewed
Everything seems to work fine, except for the logout button. Clicking it seems to do nothing, but not sure if this behavior is on my end

2021-07-07 21:37 UTC, zachmullen requested changes

2021-07-07 21:37 UTC, zachmullen commented on miqa/core/management/commands/makeclient.py
> +        client_secret='zNkKPQjc17WfVJjIyLlqpCNdE3LYFfOTF3crpSWsMFMBvxFsqxDz0q85Rgm'
IIRC, for the apps we use with SPAs, this secret value can be empty.

2021-07-08 14:55 UTC, merged